### ISSUE TITLE
配置文件有问题，第266行有非法字符

### ISSUE THREAD

**Issue by dugujian1986** [shuch36/Hackintosh-Dell-OptiPlex-7060MFF-Catalina-Big-Sur-OC#1]
配置文件有问题，第266行有非法字符，导致使用ProperTree或OpenCore Configurator修改配置文件报错。我是使用vscode修复的。另外大神有空能修复下麦克风吗？谢谢。

**Comment by shuch36** [comment]
不好意思哈，我用plistedit编辑的，非法字符不影响使用。麦那个问题，这机器是个复合接口，目前好像这类机器都没有完整且好用的方案，需要这复制需要那操作的，鄙人才疏学浅，仿冒applehda超出我能力范围了。

**Comment by dugujian1986** [comment]
> 不好意思哈，我用plistedit编辑的，非法字符不影响使用。麦那个问题，这机器是个复合接口，目前好像这类机器都没有完整且好用的方案，需要这复制需要那操作的，鄙人才疏学浅，仿冒applehda超出我能力范围了。

没关系，不过还是感谢你，谢谢你让我用到完美的黑苹果。
