### ISSUE TITLE
用OCC注入三码后重启无法进入OC

### ISSUE THREAD

**Issue by amesshen** [shuch36/Hackintosh-Dell-OptiPlex-7060MFF-Catalina-Big-Sur-OC#2]
大神好，我用了你EFI，已经成功安装了Big Sur。
不过无法登陆appleid，我按照网上的教程尝试用OCC注入三码。

重启后直接卡在OC的加载界面，错误为 OC：Configuration requires vault but no vault provided!
此时我用OCC 2.11.1.1在OC0.6.0模式下编辑config，
将Misc-Security-Vault设置为Optional
重启之后直接是无法引导，效果跟硬盘上没安装任何系统一样。

请问大神，是我的OCC版本不对，还是改过之后OCC自动改了别的选项导致出现了另外的问题。
方便的话，麻烦大神把注入好三码的config发我一份（ames@uedry.cn），我重新随机一份三码再试试。

万分感谢!

**Comment by amesshen** [comment]
看了那个已经close的issue，才发现大神是用plistEdit编辑的，怪不得OCC编辑了就不行了
用了plistEdit，已经成功洗白~再次感谢大神

**Comment by shuch36** [comment]
也不是什么大神，只是爱好而已。occ容易出错，版本不对直接gg，所以我都用plistedit编辑
