### ISSUE TITLE
想问一下cpu是8600t的可以用这个efi文件吗

### ISSUE THREAD

**Issue by DokiOnjouji** [shuch36/Hackintosh-Dell-OptiPlex-7060MFF-Catalina-Big-Sur-OC#3]

**Comment by shuch36** [comment]
应该可以，我是8100T，另外8400好像也成功了的

**Comment by DokiOnjouji** [comment]
好的，我等cpu到了试验一下哈

**Comment by 9caf** [comment]
我8600T，成功一次点亮，谢谢大大

**Comment by shuch36** [comment]
> 我8600T，成功一次点亮，谢谢大大
不知道是不是个例子，睡眠无法唤醒，你的可以唤醒不

**Comment by DokiOnjouji** [comment]
成功安装15.7并且点亮，但是有个诡异的点是图形显示卡显示了一个1050ti 而不是UHD630，升级BigSur后也是显示1050ti，不知道解码是否正常还没测试。

**Comment by shuch36** [comment]
> 成功安装15.7并且点亮，但是有个诡异的点是图形显示卡显示了一个1050ti 而不是UHD630，升级BigSur后也是显示1050ti，不知道解码是否正常还没测试。

哈哈哈，你打开配置文件搜索 1050ti把它改成uhd630就行了，那个不影响的
